# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='leaderProto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csample.proto\x12\x0bleaderProto\"\x1e\n\x0c\x42oolResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x12\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xef\x01\n\x04RAFT\x12\x36\n\x04ping\x12\x11.leaderProto.Node\x1a\x19.leaderProto.BoolResponse\"\x00\x12;\n\tsetLeader\x12\x11.leaderProto.Node\x1a\x19.leaderProto.BoolResponse\"\x00\x12=\n\x0brequestVote\x12\x11.leaderProto.Node\x1a\x19.leaderProto.BoolResponse\"\x00\x12\x33\n\tgetLeader\x12\x11.leaderProto.Node\x1a\x11.leaderProto.Node\"\x00\x62\x06proto3')
)




_BOOLRESPONSE = _descriptor.Descriptor(
  name='BoolResponse',
  full_name='leaderProto.BoolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='leaderProto.BoolResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=59,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='leaderProto.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='leaderProto.Node.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['BoolResponse'] = _BOOLRESPONSE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoolResponse = _reflection.GeneratedProtocolMessageType('BoolResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOLRESPONSE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:leaderProto.BoolResponse)
  ))
_sym_db.RegisterMessage(BoolResponse)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:leaderProto.Node)
  ))
_sym_db.RegisterMessage(Node)



_RAFT = _descriptor.ServiceDescriptor(
  name='RAFT',
  full_name='leaderProto.RAFT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='leaderProto.RAFT.ping',
    index=0,
    containing_service=None,
    input_type=_NODE,
    output_type=_BOOLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setLeader',
    full_name='leaderProto.RAFT.setLeader',
    index=1,
    containing_service=None,
    input_type=_NODE,
    output_type=_BOOLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='requestVote',
    full_name='leaderProto.RAFT.requestVote',
    index=2,
    containing_service=None,
    input_type=_NODE,
    output_type=_BOOLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getLeader',
    full_name='leaderProto.RAFT.getLeader',
    index=3,
    containing_service=None,
    input_type=_NODE,
    output_type=_NODE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['RAFT'] = _RAFT

# @@protoc_insertion_point(module_scope)
